### ISSUE TITLE
Error in documentation for sample messages

### ISSUE THREAD

**Issue by jordan2175** [TAXIIProject/TAXII-Specifications#52]
On this page: http://taxiiproject.github.io/documentation/sample-use/

In the Sample TAXII 1.1 Collection Information Response example you have listed two identical Polling_Service entries.  I do not think that is correct and would probably cause an error in someones code. 

```
        <taxii_11:Polling_Service>
            <taxii_11:Protocol_Binding>urn:taxii.mitre.org:protocol:http:1.0</taxii_11:Protocol_Binding>
            <taxii_11:Address>/services/poll/</taxii_11:Address>
            <taxii_11:Message_Binding>urn:taxii.mitre.org:message:xml:1.1</taxii_11:Message_Binding>
        </taxii_11:Polling_Service>
        <taxii_11:Polling_Service>
            <taxii_11:Protocol_Binding>urn:taxii.mitre.org:protocol:https:1.0</taxii_11:Protocol_Binding>
            <taxii_11:Address>/services/poll/</taxii_11:Address>
            <taxii_11:Message_Binding>urn:taxii.mitre.org:message:xml:1.1</taxii_11:Message_Binding>
        </taxii_11:Polling_Service>
```

**Comment by MarkDavidson** [comment]
@jordan2175,

The difference is that one service is listed for HTTP, and one service is listed for HTTPS. There is a one character difference between these two services, so it's easy to miss. The protocol binding values are different.

I've closed this because I think my comment addresses the issue as described. If it does not, please feel free to reopen.

Thank you.
-Mark
