### ISSUE TITLE
Error in XML message binding spec

### ISSUE THREAD

**Issue by jordan2175** [TAXIIProject/TAXII-Specifications#53]
In the TAXII XML Message Binding Spec on page 21, Table 9 - TAXII Collection Information Request Fields of section 3.6, the Message Binding is listed as "1" where every where else in the document Message Binding is listed as "1-n"

**Comment by MarkDavidson** [comment]
@jordan2175,

Page 21 Table 9 contains information for `Manage Collection Subscription Response`, not `Collection Information Request` as you mentioned. The `Collection Information Request` is listed in Section 3.4 on Page 14. For the rest of this response, I'll presume you meant the `Manage Collection Subscription Response` (since the `Collection Information Request` doesn't have very many fields).

As a practical matter, the error is not in the XML Message Binding Specification - it agrees with the TAXII Services Specification. The TAXII Services Specification defines the Delivery Message Binding as required and cannot have multiple values. If there is an error, it is in the TAXII Services Specification and not the XML Message Binding Specification.

As for the TAXII Services Specification/Subscription Response, I feel that an occurrence of 1 is correct. When a response is issued, a client has requested a specific delivery of content and the server is informing the client that the subscription has been granted and is detailing the specifics of future exchanges. Therefore, I think an occurrence of 1 is correct.

As for the **Request**, I think there's an argument to be made that the request could have multiple Delivery Message Binding elements - the server would then pick from these when choosing to fulfill the subscription. When writing TAXII, the idea was that the client would already know which Message Bindings were supported by the server and would be able to pick from a list of known good values.

Thoughts?

Thank you.
-Mark

**Comment by jordan2175** [comment]
No, I did mean 3.6 TAXII Manage Collection Subscription Request as part of the Push_Parameters.

**Comment by MarkDavidson** [comment]
@jordan2175 - Just to clarify, the last paragraph of my response was the relevant one? If so, this is definitely something to consider for a future revision of TAXII.

**Comment by jordan2175** [comment]
I understand now...  This should be closed as Invalid.
